### PR TITLE
Add H3 support

### PR DESCRIPTION
**Pull request by malvag**
This adds H3 support (#59) with the following "H3" dataset type. [csi-h3](https://github.com/CARV-ICS-FORTH/csi-h3) should be installed.

Example dataset definition:
```yaml
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: h3-dataset
spec:
  local:
    type: "H3"
    storageUri: "redis://redis.default.svc:6379"
    bucket: "b1"
```

### CODE REVIEW

**Comment by YiannisGkoufas** [comment]
The PR works as expected, thanks for the contribution! While I originally suggested to have the csi-h3 deployment yamls in the src directory, I realized while reviewing the PR that it might make more sense to include it instead as a Helm chart inside the directory https://github.com/datashim-io/datashim/tree/master/chart.
Is it possible to follow the approach of csi-s3 and csi-nfs that we have and include in a similar fashion a subchart for csi-h3?

**Comment by chazapis** [comment]
> The PR works as expected, thanks for the contribution! While I originally suggested to have the csi-h3 deployment yamls in the src directory, I realized while reviewing the PR that it might make more sense to include it instead as a Helm chart inside the directory https://github.com/datashim-io/datashim/tree/master/chart.
> Is it possible to follow the approach of csi-s3 and csi-nfs that we have and include in a similar fashion a subchart for csi-h3?

@YiannisGkoufas, I just transformed the YAMLs to a Helm chart, following the same conventions used in the csi-nfs and csi-h3 ones. This meant using some newer versions of the Kubernetes CSI sidecars, so I verified that csi-h3 works with these versions. The csi-h3 project has also been updated with a Helm chart and the latest versions of the sidecars as well.

**Comment by YiannisGkoufas** [comment]
Thanks @chazapis, I tried the following and I run into 2 issues:

1. Build the dataset operator with your changes ( find it in quay.io/datashim/dataset-operator:h3-amd64 )
2. Changed the entries of values.yaml to:
```
dataset-operator-chart:
  baseRepo: "quay.io/datashim"
# dockerRegistrySecret: "anothersecret"
  generatekeys:
    image: "generate-keys"
    tag: "latest"
  datasetoperator:
    image: "dataset-operator"
    tag: "h3"
```
3. Deployed redis from your yaml here https://raw.githubusercontent.com/CARV-ICS-FORTH/csi-h3/master/example/kubernetes/redis-example.yaml
4. In the root of the project issued `make manifests` (please inspect the dlf.yaml generated in release-tools to verify that everything is generated as expected)
5. Created the example dataset:
```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: h3-dataset2
spec:
  local:
    type: "H3"
    storageUri: "redis://redis.default.svc:6379"
    bucket: "b1"
```
The issues I noticed:
- The pvc gets created but times-out when mounting it on a pod (before the helm chart update it worked)
- When I delete the dataset the pv doesn't get removed so when I recreate the dataset with the same name it fails

**Comment by chazapis** [comment]
@YiannisGkoufas, I just tried out what you described and it all works out fine.
I have created a `test` branch in our fork with the changed manifests and test scripts.

I then ran:
```bash
git checkout test
kubectl apply -f ./release-tools/manifests/dlf.yaml
kubectl apply -f ./h3-example/redis-example.yaml
kubectl apply -f ./h3-example/nginx-example.yaml
kubectl port-forward svc/nginx-example 8080:80
kubectl port-forward svc/nginx-example 8888:80
```

The `h3-dataset2` PVC is created, nginx and filebrowser services start and mount it. I then go to http://127.0.0.1:8888 and add a file, which I can download from http://127.0.0.1:8080.

Upon running `kubectl delete -f ./h3-example/nginx-example.yaml`, the services are stopped, the dataset is removed, and the PVC destroyed.

**Comment by chazapis** [comment]
We managed to reproduce this. The issue was caused by a missing RBAC rule, probably necessary because of the new CSI sidecars. Now it is working as expected.

**Pull request merged**
